// <auto-generated />
namespace PhotoSharing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correctiononcommenttimestamptype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctiononcommenttimestamptype));
        
        string IMigrationMetadata.Id
        {
            get { return "201901102025238_correction-on-comment-timestamp-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
