CREATE TABLE [dbo].[image]
(
	[Id] INT NOT NULL,
	[userId] NVARCHAR (128) NOT NULL,
	[image] VARBINARY(MAX) NULL,
	[name] VARCHAR (30) NOT NULL,
	[category] VARCHAR(30) NOT NULL,
	CONSTRAINT [PK_dbo.image] PRIMARY KEY CLUSTERED (Id),
	CONSTRAINT [FK_dbo.ASPNetUsers] FOREIGN KEY (userId)
	REFERENCES AspNetUsers (Id)
	ON UPDATE CASCADE
	ON DELETE CASCADE
)
