//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class image
    {
        public int Id { get; set; }
        public string userId { get; set; }
        [Required(ErrorMessage="Please enter the image.")]
        public byte[] picture { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public byte[] date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
